# Set extended keys on (unbreaks vim keybinds)
set -s extended-keys on
set -as terminal-features 'xterm-kitty:extkeys'
set-option -g allow-passthrough on

# Set config reload keybind
unbind r
bind r source-file ~/.config/tmux/tmux.conf

# Set true color
set-option -sa terminal-overrides ",xterm*:Tc"
set -g default-terminal "tmux-256color";

# Allow mouse scrolling
set -g mouse on

# Start window/pane ids at 1
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set-option -g renumber-windows on

# Open new panes in pwd
bind '"' split-window -v -c "#{pane_current_path}"
bind % split-window -h -c "#{pane_current_path}"

# Put status bar on top
set-option -g status-position top

# Plugins
set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'catppuccin/tmux'

set -g @catppuccin_flavor 'mocha'
set -g @catppuccin_window_status_style "rounded"

set -g status-right-length 100
set -g status-left-length 100
set -g status-left ""
set -g status-right "#{E:@catppuccin_status_application}#{E:@catppuccin_status_session}"

# Initialize TMUX plugin manager (keep this line at the very bottom of tmux.conf)
run ~/.config/tmux/plugins/tpm/tpm
